In [4]:
# Why PyTorch ?

# 1. 支持GPU加速的张量积算
# 2. 方便优化模型的自动微分机制


# 一、张量数据类型
# Pytorch基本数据结构是Tensor，即多维数组，与numpy的array类似

# Includs：
# torch.float64 (torch.double)
# torch.float32 (torch.float)
# torch.float16

# torch.ini64(torch.long)
# torch.int32(torch.int)
# torch.int16
# torch.int8
# torch.uint8
# torch.bool

# 一般神经网络建模使用的是torch.float32

import numpy as np
import torch

# 1. 自动判断数据类型

i = torch.tensor(1)
print(i,i.dtype)
x = torch.tensor(2.0)
print(x,x.dtype)
b = torch.tensor(True)
print(b,b.dtype)

tensor(1) torch.int64
tensor(2.) torch.float32
tensor(True) torch.bool


In [5]:
# 2. 指定数据类型

i = torch.tensor(1,dtype = torch.int32)
print(i,i.dtype)
x = torch.tensor(2.0,dtype = torch.double)
print(x,x.dtype)

tensor(1, dtype=torch.int32) torch.int32
tensor(2., dtype=torch.float64) torch.float64


In [6]:
# 3. 使用特定类型构造函数

i = torch.IntTensor(1)
print(i,i.dtype)
x = torch.Tensor(np.array(2.0)) #等价于torch.FloatTensor
print(x,x.dtype)
b = torch.BoolTensor(np.array([1,0,2,0]))
print(b,b.dtype)

tensor([0], dtype=torch.int32) torch.int32
tensor(2.) torch.float32
tensor([ True, False,  True, False]) torch.bool


In [7]:
# 4. 不同类型进行转换

i = torch.tensor(1)
print(i,i.dtype)
x = i.float()
# 调用float方法转换成浮点类型
print(x,x.dtype)
y = i.type(torch.float)
# 使用type函数转换成浮点类型
print(y,y.dtype)
z = i.type_as(x)
# 使用type_as方法转换成某个Tensor相同类型
print(z,z.dtype)

tensor(1) torch.int64
tensor(1.) torch.float32
tensor(1.) torch.float32
tensor(1.) torch.float32


In [8]:
# 二、 张量的维度
# 不同类型的数据可以用不同维度的张量来表示。

# 标量为0维张量，
# 向量为1维张量，
# 矩阵为2维张量，
# RGB可以表述为3为张量。
# 视频时间维可以表示为4维张量。

# 简单理解为：有几层中括号就是几维张量。

# 1. 标量
scalar = torch.tensor(True)
print(scalar)
print(scalar.dim())


tensor(True)
0


In [9]:
# 2. 向量
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(vector)
print(vector.dim())

tensor([1., 2., 3., 4.])
1


In [11]:
# 3. 矩阵
matrix = torch.tensor([[1.0,2.0], [3.0,4.0]])
print(matrix)
print(matrix.dim())

tensor([[1., 2.],
        [3., 4.]])
2


In [12]:
# 4. 三维张量
matrix = torch.tensor([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0], [7.0,8.0]]])
print(matrix)
print(matrix.dim())

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
3


In [13]:
# 5. 四维张量
tensor4 = torch.tensor([[[[1.0,1.0],[2.0,2.0]],[[3.0,3.0],[4.0,4.0]]],                        
                        [[[5.0,5.0],[6.0,6.0]],[[7.0,7.0],[8.0,8.0]]]])

print(tensor4)
print(tensor4.dim())

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]]],


        [[[5., 5.],
          [6., 6.]],

         [[7., 7.],
          [8., 8.]]]])
4


In [14]:
# 三、 张量的尺寸
# 使用shape属性或者size()方法查看每一维度的长度
# 使用view()方法改变张量尺寸。
# 如果fail，使用reshape()方法

scalar  = torch.tensor(True)
# 查看长度
print(scalar.size())
print(vector.shape)

torch.Size([])
torch.Size([4])


In [16]:
vector = torch.tensor([1.0,2.0,3.0,4.0])
print(vector.size())
print(vector.shape)

torch.Size([4])
torch.Size([4])


In [19]:
matrix = torch.tensor([[1.0,2.0],[3.0,4.0]])
print(matrix.size())
print(matrix.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [22]:
# 使用view改变张量尺寸操作：

vector = torch.arange(0,12)
print(vector)
print(vector.shape)

matrix34 = vector.view(3,4)
print(matrix34)
print(matrix.shape)

matrix43 = vector.view(4,-1) #-1表示该位置长度由程序自动判断
print(matrix43)
print(matrix.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([2, 2])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 2])


In [24]:
# 有些方法会让张量存储结构扭曲
# 直接使用view会失败
# 这时候应该使用reshape方法

matrix26 = torch.arange(0,12).view(2,6)
print(matrix26)
print(matrix26.shape)

# 转置操作让张良存储结构扭曲

matrix62 = matrix26.t()
print(matrix62.is_contiguous())

# 这时候使用view会失败。这时候要用reshape

# matrix34 = matrix62.view(3,4) Error！！！！
matrix34 = matrix62.reshape(3,4)
print(matrix34)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
False
tensor([[ 0,  6,  1,  7],
        [ 2,  8,  3,  9],
        [ 4, 10,  5, 11]])


In [26]:
# 四、 张量和numpy数组

# 可以用numpy方法从Tensor得到numpy数组，

# 也可以用torch.from_numpy从numpy数组得到Tensor

# 这两种方法关联的Tensor和numpy数组是共享数据内存的。 

# 如果改变其中一个，另外一个的值也会发生改变。 

# 如果有需要，可以用张量的clone方法拷贝张量，中断这种关联 ！！！！！！

# 此外，还可以使用item方法从标量张量得到对应的Python数值。 

# 使用tolist方法从张量得到对应的Python数值列表。

import numpy as np
import torch

# 1. torch.from_numpy函数从numpy数组获取Tensor
arr = np.zeros(3)
tensor = torch.from_numpy(arr)
print("before add 1 :")
print(arr)
print(tensor)

print("\n after add 1 :")
np.add(arr,1,out = arr) #给arr增加1，tensor也会随之改变!!!!!!!
print(arr)
print(tensor)

before add 1 :
[0. 0. 0.]
tensor([0., 0., 0.], dtype=torch.float64)

 after add 1 :
[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


In [27]:
# 2. numpy方法从Tensor得到数组

tensor = torch.zeros(3)
arr = tensor.numpy()
print("before add 1 :")
print(tensor)
print(arr)

tensor.add_(1)
# 或者torch.add(tensor,1,out = tensor)

print(tensor)
print(arr)

before add 1 :
tensor([0., 0., 0.])
[0. 0. 0.]
tensor([1., 1., 1.])
[1. 1. 1.]


In [28]:
# 3. 使用clone方法拷贝张量，中断联系

tensor = torch.zeros(3)
arr = tensor.clone().numpy()
print("before add 1 :")
print(tensor)
print(arr)

# 使用带下划线的方法表示计算结果会返回给调用张量
print("\nafter add 1 ：")

tensor.add_(1)
print(tensor)
print(arr)

before add 1 :
tensor([0., 0., 0.])
[0. 0. 0.]

after add 1 ：
tensor([1., 1., 1.])
[0. 0. 0.]


In [30]:
# 4. item方法和tolist方法可以将tensor转换成python数值和数值列表

scalar = torch.tensor(1.0)
s = scalar.item()
print(s)
print(type(s))

tensor = torch.rand(2,2)
t = tensor.tolist()
print(tensor)
print(t)
print(type(t))

1.0
<class 'float'>
tensor([[0.9456, 0.7354],
        [0.4509, 0.4178]])
[[0.9456409215927124, 0.7354218363761902], [0.4508856534957886, 0.4177810549736023]]
<class 'list'>
