In [4]:
# Why PyTorch ?

# 1. 支持GPU加速的张量积算
# 2. 方便优化模型的自动微分机制


# 一、张量数据类型
# Pytorch基本数据结构是Tensor，即多维数组，与numpy的array类似

# Includs：
# torch.float64 (torch.double)
# torch.float32 (torch.float)
# torch.float16

# torch.ini64(torch.long)
# torch.int32(torch.int)
# torch.int16
# torch.int8
# torch.uint8
# torch.bool

# 一般神经网络建模使用的是torch.float32

import numpy as np
import torch

# 1. 自动判断数据类型

i = torch.tensor(1)
print(i,i.dtype)
x = torch.tensor(2.0)
print(x,x.dtype)
b = torch.tensor(True)
print(b,b.dtype)

tensor(1) torch.int64
tensor(2.) torch.float32
tensor(True) torch.bool


In [5]:
# 2. 指定数据类型

i = torch.tensor(1,dtype = torch.int32)
print(i,i.dtype)
x = torch.tensor(2.0,dtype = torch.double)
print(x,x.dtype)

tensor(1, dtype=torch.int32) torch.int32
tensor(2., dtype=torch.float64) torch.float64


In [6]:
# 3. 使用特定类型构造函数

i = torch.IntTensor(1)
print(i,i.dtype)
x = torch.Tensor(np.array(2.0)) #等价于torch.FloatTensor
print(x,x.dtype)
b = torch.BoolTensor(np.array([1,0,2,0]))
print(b,b.dtype)

tensor([0], dtype=torch.int32) torch.int32
tensor(2.) torch.float32
tensor([ True, False,  True, False]) torch.bool


In [7]:
# 4. 不同类型进行转换

i = torch.tensor(1)
print(i,i.dtype)
x = i.float()
# 调用float方法转换成浮点类型
print(x,x.dtype)
y = i.type(torch.float)
# 使用type函数转换成浮点类型
print(y,y.dtype)
z = i.type_as(x)
# 使用type_as方法转换成某个Tensor相同类型
print(z,z.dtype)

tensor(1) torch.int64
tensor(1.) torch.float32
tensor(1.) torch.float32
tensor(1.) torch.float32


In [8]:
# 二、 张量的维度
# 不同类型的数据可以用不同维度的张量来表示。

# 标量为0维张量，
# 向量为1维张量，
# 矩阵为2维张量，
# RGB可以表述为3为张量。
# 视频时间维可以表示为4维张量。

# 简单理解为：有几层中括号就是几维张量。

# 1. 标量
scalar = torch.tensor(True)
print(scalar)
print(scalar.dim())


tensor(True)
0


In [9]:
# 2. 向量
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(vector)
print(vector.dim())

tensor([1., 2., 3., 4.])
1


In [11]:
# 3. 矩阵
matrix = torch.tensor([[1.0,2.0], [3.0,4.0]])
print(matrix)
print(matrix.dim())

tensor([[1., 2.],
        [3., 4.]])
2


In [12]:
# 4. 三维张量
matrix = torch.tensor([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0], [7.0,8.0]]])
print(matrix)
print(matrix.dim())

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
3


In [13]:
# 5. 四维张量
tensor4 = torch.tensor([[[[1.0,1.0],[2.0,2.0]],[[3.0,3.0],[4.0,4.0]]],                        
                        [[[5.0,5.0],[6.0,6.0]],[[7.0,7.0],[8.0,8.0]]]])

print(tensor4)
print(tensor4.dim())

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]]],


        [[[5., 5.],
          [6., 6.]],

         [[7., 7.],
          [8., 8.]]]])
4


In [ ]:
# 三、 张量的尺寸
# 使用shape属性或者size()方法查看每一维度的长度
# 使用view()方法改变张量尺寸。
# 如果fail，使用reshape()方法

