In [1]:
# 张量的操作主要包括张量的结构操作和张量的数学运算。

# 张量结构操作诸如：张量创建，索引切片，维度变换，合并分割。

# 张量数学运算主要有：标量运算，向量运算，矩阵运算。

# 另外我们会介绍张量运算的广播机制！！！

In [2]:
# 一、 创建张量

import numpy as np 
import torch

a = torch.tensor([1,2,3], dtype = torch.float)
print(a)

tensor([1., 2., 3.])


In [8]:
b = torch.arange(1,10,step = 2)
print(b)

tensor([1, 3, 5, 7, 9])


In [9]:
c = torch.linspace(0.0,2*3.14,10)
print(c)

tensor([0.0000, 0.6978, 1.3956, 2.0933, 2.7911, 3.4889, 4.1867, 4.8844, 5.5822,
        6.2800])


In [10]:
d = torch.zeros((3,3))
print(d)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
a = torch.ones((3,3), dtype = torch.int)
b = torch.zeros_like(a, dtype = torch.float)
print(a)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [13]:
torch.fill_(b,5)
print(b)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


In [19]:
# 均匀随机分布 ！！！！

torch.manual_seed(0)
minval, maxval = 0,10
a = minval + (maxval - minval)*torch.rand([5])
print(a)

tensor([4.9626, 7.6822, 0.8848, 1.3203, 3.0742])


In [20]:
# 正态分布随机 ！！！！

b = torch.normal(mean = torch.zeros(3,3), std = torch.ones(3,3))
print(b)

tensor([[ 0.5507,  0.2704,  0.6472],
        [ 0.2490, -0.3354,  0.4564],
        [-0.6255,  0.4539, -1.3740]])


In [21]:
# 正态分布随机！！！！

mean, std = 2,5
c = std * torch.randn((3,3)) + mean
print(c)

tensor([[16.2371, -1.6612,  3.9163],
        [ 7.4999,  1.5616,  4.0768],
        [ 5.2128, -8.9407,  6.4601]])


In [22]:
# 整数随机排列

d = torch.randperm(20)
print(d)

tensor([ 3, 17,  9, 19,  1, 18,  4, 13, 15, 12,  0, 16,  7, 11,  2,  5,  8, 10,
         6, 14])


In [24]:
# 特殊矩阵

I = torch.eye(3,3) #单位矩阵
print(I)
t = torch.diag(torch.tensor([1,2,3])) #对角矩阵
print(t)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


In [50]:
# 二、 索引切片

# 张量的索引切片方式和numpy几乎是一样的。

# 切片时支持缺省参数和省略号。

# 可以通过索引和切片对部分元素进行修改。

# 此外，对于不规则的切片提取,

# 可以使用

# 1. torch.index_select, 

# 2. torch.masked_select, 

# 3. torch.take

# 如果要通过修改张量的某些元素得到新的张量，

# 可以使用

# 1. torch.where,

# 2. torch.masked_fill,

# 3. torch.index_fill


# 均匀随机分布
torch.manual_seed(0)
minval, maxval = 0,10
t = torch.floor(minval + (maxval - minval)*torch.rand([5,5])).int()
print(t)

tensor([[4, 7, 0, 1, 3],
        [6, 4, 8, 4, 6],
        [3, 4, 0, 1, 2],
        [5, 6, 8, 1, 2],
        [6, 9, 3, 8, 4]], dtype=torch.int32)


In [51]:
print(t[0])
# 打印第0维张量

tensor([4, 7, 0, 1, 3], dtype=torch.int32)


In [52]:
print(t[-1])
# 打印到数第一维度张量

tensor([6, 9, 3, 8, 4], dtype=torch.int32)


In [53]:
# 打印第一维张量的第四个
print(t[1,3])
print(t[1][3])

tensor(4, dtype=torch.int32)
tensor(4, dtype=torch.int32)


In [56]:
# 第一维至第三维

print(t[1:4,:])

tensor([[6, 4, 8, 4, 6],
        [3, 4, 0, 1, 2],
        [5, 6, 8, 1, 2]], dtype=torch.int32)


In [57]:
#第1行至最后一行，
#第0列到最后一列每隔两列取一列
print(t[1:4,:4:2])

tensor([[6, 8],
        [3, 0],
        [5, 8]], dtype=torch.int32)


In [62]:
x = torch.tensor([[1,2],[3,4]],dtype = torch.float32,requires_grad=True)
print(x)]

#可以使用索引和切片修改部分元素!!!!!!!

x.data[1,:] = torch.tensor([0.0,0.0])
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [0., 0.]], requires_grad=True)


In [63]:
a = torch.arange(27).view(3,3,3)
print(a)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


In [67]:
#省略号可以表示多个冒号
print(a[...,0])
print(a[...,1])
print(a[...,2])

tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])
tensor([[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]])
tensor([[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]])


In [69]:
# 以上切片方式相对规则，对于不规则的切片提取,可以使用:

# torch.index_select, 

# torch.take, 

# torch.gather, 

# torch.masked_select.

# 考虑班级成绩册的例子，有4个班级，每个班级10个学生，
# 每个学生7门科目成绩。可以用一个4×10×7的张量来表示。

minval=0
maxval=100
scores = torch.floor(minval + (maxval-minval)*torch.rand([4,10,7])).int()
print(scores)

tensor([[[12, 58, 71, 69, 43,  9, 42],
         [67, 31, 68, 83, 23, 50, 70],
         [53, 54, 56, 10, 53, 84, 95],
         [79, 56, 73, 25,  8,  7, 99],
         [81, 15, 69, 87, 99, 93, 88],
         [38, 32, 91, 78, 19, 94, 74],
         [77, 18, 64, 32, 89, 41, 69],
         [58, 71, 33, 74, 15, 61, 16],
         [ 0,  9, 89, 77, 96, 90,  5],
         [15, 41, 17, 84, 12, 25,  1]],

        [[21, 91, 90, 85, 88, 94, 37],
         [72, 94, 66, 99, 75, 81, 32],
         [73, 55, 38, 21, 21, 11, 83],
         [85, 44, 21, 88, 81, 53, 26],
         [95, 70, 12, 97, 87, 31, 78],
         [21, 42, 92, 52, 14, 33, 36],
         [40, 54, 96, 52, 19, 52, 73],
         [74,  4, 41, 12, 28, 68, 14],
         [68, 92, 53, 16, 32, 60, 11],
         [74,  4,  1,  1, 39, 83,  2]],

        [[91, 29, 64, 52,  4, 91, 76],
         [99, 75, 16, 91, 52, 73,  9],
         [35,  0, 30, 60, 10, 65, 76],
         [56, 16, 11, 34, 71, 99, 78],
         [44, 67,  0,  7, 73, 21, 74],
         [14, 25,  8,

In [70]:
#抽取每个班级  第0个学生，第5个学生，第10个学生的全部成绩
torch.index_select(scores,dim = 1,index = torch.tensor([0,5,9]))

tensor([[[12, 58, 71, 69, 43,  9, 42],
         [38, 32, 91, 78, 19, 94, 74],
         [15, 41, 17, 84, 12, 25,  1]],

        [[21, 91, 90, 85, 88, 94, 37],
         [21, 42, 92, 52, 14, 33, 36],
         [74,  4,  1,  1, 39, 83,  2]],

        [[91, 29, 64, 52,  4, 91, 76],
         [14, 25,  8, 76, 44, 88, 80],
         [35, 66, 35, 80, 36, 31, 62]],

        [[67, 25, 54, 78, 45, 65, 37],
         [ 2,  2, 99, 18, 59, 45, 39],
         [70, 98, 35,  8,  4, 62, 46]]], dtype=torch.int32)

In [71]:
#抽取每个班级第0个学生，第5个学生，第10个学生的
#            第1门课程，第4门课程，第7门课程成绩
q = torch.index_select(torch.index_select(scores,dim = 1,index = torch.tensor([0,5,9]))
                   ,dim=2,index = torch.tensor([1,3,6]))
print(q)

tensor([[[58, 69, 42],
         [32, 78, 74],
         [41, 84,  1]],

        [[91, 85, 37],
         [42, 52, 36],
         [ 4,  1,  2]],

        [[29, 52, 76],
         [25, 76, 80],
         [66, 80, 62]],

        [[25, 78, 37],
         [ 2, 18, 39],
         [98,  8, 46]]], dtype=torch.int32)


In [73]:
#抽取第1个班级第1个学生的第1门课程，
#第3个班级的第5个学生的第2门课程，
#第4个班级的第10个学生第7门课程成绩
#take将输入看成一维数组，输出和index同形状

s = torch.take(scores,torch.tensor([0*10*7+0,2*10*7+4*7+1,3*10*7+9*7+6]))
s

tensor([12, 67, 46], dtype=torch.int32)

In [74]:
#抽取分数大于等于80分的分数（布尔索引）
#结果是1维张量
g = torch.masked_select(scores,scores>=80)
print(g)

tensor([83, 84, 95, 99, 81, 87, 99, 93, 88, 91, 94, 89, 89, 96, 90, 84, 91, 90,
        85, 88, 94, 94, 99, 81, 83, 85, 88, 81, 95, 97, 87, 92, 96, 92, 83, 91,
        91, 99, 91, 99, 88, 80, 91, 94, 95, 85, 92, 80, 95, 99, 98, 91, 99, 99,
        81, 97, 89, 92, 91, 98], dtype=torch.int32)


In [75]:
# 以上这些方法仅能提取张量的部分元素值，

# 但不能更改张量的部分元素值得到新的张量。

# 如果要通过修改张量的部分元素值得到新的张量，

# 可以使用

# torch.where,torch.index_fill 和 torch.masked_fill

# torch.where可以理解为if的张量版本。

# torch.index_fill的选取元素逻辑和torch.index_select相同。

# torch.masked_fill的选取元素逻辑和torch.masked_select相同。

ifpass = torch.where(scores>60, torch.tensor(1), torch.tensor(0))
print(ifpass)

tensor([[[0, 0, 1, 1, 0, 0, 0],
         [1, 0, 1, 1, 0, 0, 1],
         [0, 0, 0, 0, 0, 1, 1],
         [1, 0, 1, 0, 0, 0, 1],
         [1, 0, 1, 1, 1, 1, 1],
         [0, 0, 1, 1, 0, 1, 1],
         [1, 0, 1, 0, 1, 0, 1],
         [0, 1, 0, 1, 0, 1, 0],
         [0, 0, 1, 1, 1, 1, 0],
         [0, 0, 0, 1, 0, 0, 0]],

        [[0, 1, 1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1, 1, 0],
         [1, 0, 0, 0, 0, 0, 1],
         [1, 0, 0, 1, 1, 0, 0],
         [1, 1, 0, 1, 1, 0, 1],
         [0, 0, 1, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 1],
         [1, 0, 0, 0, 0, 1, 0],
         [1, 1, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 1, 0]],

        [[1, 0, 1, 0, 0, 1, 1],
         [1, 1, 0, 1, 0, 1, 0],
         [0, 0, 0, 0, 0, 1, 1],
         [0, 0, 0, 0, 1, 1, 1],
         [0, 1, 0, 0, 1, 0, 1],
         [0, 0, 0, 1, 0, 1, 1],
         [1, 0, 0, 0, 0, 1, 0],
         [1, 0, 0, 0, 1, 1, 0],
         [1, 1, 1, 1, 0, 1, 1],
         [0, 1, 0, 1, 0, 0, 1]],

        [[1, 0, 0, 1, 0, 1, 0],
  

In [78]:
#将每个班级第0个学生，第5个学生，第9个学生的全部成绩赋值成满分
torch.index_fill(scores, dim = 1, index = torch.tensor([0,5,9]), value = 100)

tensor([[[100, 100, 100, 100, 100, 100, 100],
         [ 67,  31,  68,  83,  23,  50,  70],
         [ 53,  54,  56,  10,  53,  84,  95],
         [ 79,  56,  73,  25,   8,   7,  99],
         [ 81,  15,  69,  87,  99,  93,  88],
         [100, 100, 100, 100, 100, 100, 100],
         [ 77,  18,  64,  32,  89,  41,  69],
         [ 58,  71,  33,  74,  15,  61,  16],
         [  0,   9,  89,  77,  96,  90,   5],
         [100, 100, 100, 100, 100, 100, 100]],

        [[100, 100, 100, 100, 100, 100, 100],
         [ 72,  94,  66,  99,  75,  81,  32],
         [ 73,  55,  38,  21,  21,  11,  83],
         [ 85,  44,  21,  88,  81,  53,  26],
         [ 95,  70,  12,  97,  87,  31,  78],
         [100, 100, 100, 100, 100, 100, 100],
         [ 40,  54,  96,  52,  19,  52,  73],
         [ 74,   4,  41,  12,  28,  68,  14],
         [ 68,  92,  53,  16,  32,  60,  11],
         [100, 100, 100, 100, 100, 100, 100]],

        [[100, 100, 100, 100, 100, 100, 100],
         [ 99,  75,  16,  91, 

In [79]:
#将分数小于60分的分数赋值成60分
b = torch.masked_fill(scores,scores<60,60)
#等价于b = scores.masked_fill(scores<60,60)
b

tensor([[[60, 60, 71, 69, 60, 60, 60],
         [67, 60, 68, 83, 60, 60, 70],
         [60, 60, 60, 60, 60, 84, 95],
         [79, 60, 73, 60, 60, 60, 99],
         [81, 60, 69, 87, 99, 93, 88],
         [60, 60, 91, 78, 60, 94, 74],
         [77, 60, 64, 60, 89, 60, 69],
         [60, 71, 60, 74, 60, 61, 60],
         [60, 60, 89, 77, 96, 90, 60],
         [60, 60, 60, 84, 60, 60, 60]],

        [[60, 91, 90, 85, 88, 94, 60],
         [72, 94, 66, 99, 75, 81, 60],
         [73, 60, 60, 60, 60, 60, 83],
         [85, 60, 60, 88, 81, 60, 60],
         [95, 70, 60, 97, 87, 60, 78],
         [60, 60, 92, 60, 60, 60, 60],
         [60, 60, 96, 60, 60, 60, 73],
         [74, 60, 60, 60, 60, 68, 60],
         [68, 92, 60, 60, 60, 60, 60],
         [74, 60, 60, 60, 60, 83, 60]],

        [[91, 60, 64, 60, 60, 91, 76],
         [99, 75, 60, 91, 60, 73, 60],
         [60, 60, 60, 60, 60, 65, 76],
         [60, 60, 60, 60, 71, 99, 78],
         [60, 67, 60, 60, 73, 60, 74],
         [60, 60, 60,

In [80]:
# 三，维度变换
# 维度变换相关函数主要有 
# torch.reshape(或者调用张量的view方法), torch.squeeze, torch.unsqueeze, torch.transpose

# torch.reshape 可以改变张量的形状。

# torch.squeeze 可以减少维度。

# torch.unsqueeze 可以增加维度。

# torch.transpose 可以交换维度。

# 张量的view方法有时候会调用失败，可以使用reshape方法。
torch.manual_seed(0)
minval,maxval = 0,255
a = (minval + (maxval-minval)*torch.rand([1,3,3,2])).int()
print(a.shape)
print(a)

torch.Size([1, 3, 3, 2])
tensor([[[[126, 195],
          [ 22,  33],
          [ 78, 161]],

         [[124, 228],
          [116, 161],
          [ 88, 102]],

         [[  5,  43],
          [ 74, 132],
          [177, 204]]]], dtype=torch.int32)


In [81]:
# 改成 （3,6）形状的张量
b = a.view([3,6]) #torch.reshape(a,[3,6])
print(b.shape)
print(b)

torch.Size([3, 6])
tensor([[126, 195,  22,  33,  78, 161],
        [124, 228, 116, 161,  88, 102],
        [  5,  43,  74, 132, 177, 204]], dtype=torch.int32)


In [82]:
# 改回成 [1,3,3,2] 形状的张量
c = torch.reshape(b,[1,3,3,2]) # b.view([1,3,3,2]) 
print(c)

tensor([[[[126, 195],
          [ 22,  33],
          [ 78, 161]],

         [[124, 228],
          [116, 161],
          [ 88, 102]],

         [[  5,  43],
          [ 74, 132],
          [177, 204]]]], dtype=torch.int32)


In [83]:
# 如果张量在某个维度上只有一个元素，利用torch.squeeze可以消除这个维度。
# torch.unsqueeze的作用和torch.squeeze的作用相反。
a = torch.tensor([[1.0,2.0]])
s = torch.squeeze(a)
print(a)
print(s)
print(a.shape)
print(s.shape)

tensor([[1., 2.]])
tensor([1., 2.])
torch.Size([1, 2])
torch.Size([2])


In [84]:
d = torch.unsqueeze(s,axis=0)  
print(s)
print(d)

print(s.shape)
print(d.shape)

tensor([1., 2.])
tensor([[1., 2.]])
torch.Size([2])
torch.Size([1, 2])


In [85]:
# torch.transpose可以交换张量的维度，
# torch.transpose常用于图片存储格式的变换上。
# 如果是二维的矩阵，通常会调用矩阵的转置方法 matrix.t()，
# 等价于 torch.transpose(matrix,0,1)。

minval=0
maxval=255
# Batch,Height,Width,Channel
data = torch.floor(minval + (maxval-minval)*torch.rand([100,256,256,4])).int()
print(data.shape)

# 转换成 Pytorch默认的图片格式 Batch,Channel,Height,Width 
# 需要交换两次
data_t = torch.transpose(torch.transpose(data,1,2),1,3)
print(data_t.shape)

torch.Size([100, 256, 256, 4])
torch.Size([100, 4, 256, 256])


In [86]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.t()) #等价于torch.transpose(matrix,0,1)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [87]:
# 四，合并分割
# 可以用torch.cat方法和torch.stack方法将多个张量合并，

# 可以用torch.split方法把一个张量分割成多个张量。

# torch.cat和torch.stack有略微的区别，

# torch.cat是连接，不会增加维度，

# 而torch.stack是堆叠，会增加维度。

a = torch.tensor([[1.0,2.0],[3.0,4.0]])
b = torch.tensor([[5.0,6.0],[7.0,8.0]])
c = torch.tensor([[9.0,10.0],[11.0,12.0]])

abc_cat = torch.cat([a,b,c],dim = 0)
print(abc_cat.shape)
print(abc_cat)

torch.Size([6, 2])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [88]:
abc_stack = torch.stack([a,b,c],axis = 0) #torch中dim和axis参数名可以混用
print(abc_stack.shape)
print(abc_stack)

torch.Size([3, 2, 2])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [89]:
torch.cat([a,b,c],axis = 1)

tensor([[ 1.,  2.,  5.,  6.,  9., 10.],
        [ 3.,  4.,  7.,  8., 11., 12.]])

In [90]:
torch.stack([a,b,c],axis = 1)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])

In [91]:
# torch.split是torch.cat的逆运算，
# 可以指定分割份数平均分割，
# 也可以通过指定每份的记录数量进行分割。

print(abc_cat)
a,b,c = torch.split(abc_cat,split_size_or_sections = 2,dim = 0) #每份2个进行分割
print(a)
print(b)
print(c)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [92]:
print(abc_cat)
p,q,r = torch.split(abc_cat,split_size_or_sections =[4,1,1],dim = 0) #每份分别为[4,1,1]
print(p)
print(q)
print(r)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[ 9., 10.]])
tensor([[11., 12.]])
