In [1]:
# 张量数学运算主要有：标量运算，向量运算，矩阵运算。
# 另外还有张量运算的广播机制。

# 一、 标量运算

# 张量的数学运算符可以分为标量运算符、向量运算符、以及矩阵运算符。
# 加减乘除乘方，以及三角函数，指数，对数等常见函数，逻辑比较运算符等都是标量运算符。
# 标量运算符的特点是对张量实施逐元素运算。
# 有些标量运算符对常用的数学运算符进行了重载。并且支持类似numpy的广播特性。

import torch
import numpy as np

a = torch.tensor([[1.0,2], [-3, 4.0]])
b = torch.tensor([[9.0,6], [7.0,8.0]])
a+b

tensor([[10.,  8.],
        [ 4., 12.]])

In [2]:
a-b

tensor([[ -8.,  -4.],
        [-10.,  -4.]])

In [4]:
a*b

tensor([[  9.,  12.],
        [-21.,  32.]])

In [5]:
a/b

tensor([[ 0.1111,  0.3333],
        [-0.4286,  0.5000]])

In [6]:
a**2

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [7]:
a**(0.5)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [8]:
a%3 #求模

tensor([[1., 2.],
        [-0., 1.]])

In [9]:
#地板除法!!!!!

a//3

C:\Users\JayphoneLin\anaconda3\envs\pytorch_study\lib\site-packages\torch\_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ..\aten\src\ATen\native\BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)


tensor([[ 0.,  0.],
        [-1.,  1.]])

In [10]:
a>=2 # torch.ge(a,2)  #ge: greater_equal缩写

tensor([[False,  True],
        [False,  True]])

In [11]:
(a>=2)&(a<=3)

tensor([[False,  True],
        [False, False]])

In [12]:
(a>=2)|(a<=3)

tensor([[True, True],
        [True, True]])

In [13]:
a==5 #torch.eq(a,5)

tensor([[False, False],
        [False, False]])

In [14]:
torch.sqrt(a)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [15]:
a = torch.tensor([1.0,8.0])
b = torch.tensor([5.0,6.0])
c = torch.tensor([6.0,7.0])

d = a+b+c
print(d)

tensor([12., 21.])


In [18]:
print(torch.max(a,b))
#每一列最大值

tensor([5., 8.])


In [19]:
print(torch.min(a,b))

tensor([1., 6.])


In [20]:
x = torch.tensor([2.6,-2.7])

print(torch.round(x)) #保留整数部分，四舍五入
print(torch.floor(x)) #保留整数部分，向下归整
print(torch.ceil(x))  #保留整数部分，向上归整
print(torch.trunc(x)) #保留整数部分，向0归整

tensor([ 3., -3.])
tensor([ 2., -3.])
tensor([ 3., -2.])
tensor([ 2., -2.])


In [21]:
x = torch.tensor([2.6,-2.7])
print(torch.fmod(x,2)) #作除法取余数 
print(torch.remainder(x,2)) #作除法取剩余的部分，结果恒正！！

tensor([ 0.6000, -0.7000])
tensor([0.6000, 1.3000])


In [22]:
# 幅值裁剪
x = torch.tensor([0.9,-0.8,100.0,-20.0,0.7])
y = torch.clamp(x,min=-1,max = 1)
z = torch.clamp(x,max = 1)
print(y)
print(z)

tensor([ 0.9000, -0.8000,  1.0000, -1.0000,  0.7000])
tensor([  0.9000,  -0.8000,   1.0000, -20.0000,   0.7000])


In [26]:
# 二，向量运算
# 向量运算符只在一个特定轴上运算，将一个向量映射到一个标量或者另外一个向量。

#统计值

a = torch.arange(1,10).float()
print(torch.sum(a)) 
print(torch.mean(a)) #平均值
print(torch.max(a))
print(torch.min(a))
print(torch.prod(a)) #累乘
print(torch.std(a))  #标准差
print(torch.var(a))  #方差
print(torch.median(a)) #中位数

tensor(45.)
tensor(5.)
tensor(9.)
tensor(1.)
tensor(362880.)
tensor(2.7386)
tensor(7.5000)
tensor(5.)


In [27]:
#指定维度计算统计值

b = a.view(3,3)
print(b)
print(torch.max(b,dim = 0))
print(torch.max(b,dim = 1))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))


In [29]:
#cum扫描
a = torch.arange(1,10)
print(a)

print(torch.cumsum(a,0)) #每一项都是前面项之和
print(torch.cumprod(a,0)) #累乘
print(torch.cummax(a,0).values) #值
print(torch.cummax(a,0).indices) #下标
print(torch.cummin(a,0))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  3,  6, 10, 15, 21, 28, 36, 45])
tensor([     1,      2,      6,     24,    120,    720,   5040,  40320, 362880])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.return_types.cummin(
values=tensor([1, 1, 1, 1, 1, 1, 1, 1, 1]),
indices=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]))


In [30]:
#torch.sort和torch.topk可以对张量排序
a = torch.tensor([[9,7,8],[1,3,2],[5,6,4]]).float()

print(torch.topk(a,2,dim = 0),"\n")

print(torch.topk(a,2,dim = 1),"\n")

print(torch.sort(a,dim = 1),"\n")

#利用torch.topk可以在Pytorch中实现KNN算法

torch.return_types.topk(
values=tensor([[9., 7., 8.],
        [5., 6., 4.]]),
indices=tensor([[0, 0, 0],
        [2, 2, 2]])) 

torch.return_types.topk(
values=tensor([[9., 8.],
        [3., 2.],
        [6., 5.]]),
indices=tensor([[0, 2],
        [1, 2],
        [1, 0]])) 

torch.return_types.sort(
values=tensor([[7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.]]),
indices=tensor([[1, 2, 0],
        [0, 2, 1],
        [2, 0, 1]])) 



In [31]:
# 三，矩阵运算
# 矩阵必须是二维的。
# 类似torch.tensor([1,2,3])这样的不是矩阵。
# 矩阵运算包括：
# 1. 矩阵乘法，
# 2. 矩阵转置，
# 3. 矩阵逆，
# 4. 矩阵求迹，
# 5. 矩阵范数，
# 6. 矩阵行列式，
# 7. 矩阵求特征值，
# 8. 矩阵分解等运算。

#矩阵乘法
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[2,0],[0,2]])
print(a@b)  #等价于torch.matmul(a,b) 或 torch.mm(a,b)

tensor([[2, 4],
        [6, 8]])


In [34]:
#矩阵转置
a = torch.tensor([[1.0,2],[3,4]])
print(a)
print(a.t())

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 3.],
        [2., 4.]])


In [33]:
#矩阵逆，必须为浮点类型
a = torch.tensor([[1.0,2],[3,4]])
print(torch.inverse(a))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [35]:
#矩阵求trace
a = torch.tensor([[1.0,2],[3,4]])
# 迹就是矩阵主对角线元素之和。
print(torch.trace(a))

tensor(5.)


In [36]:
#矩阵求范数
a = torch.tensor([[1.0,2],[3,4]])
print(torch.norm(a))

tensor(5.4772)


In [37]:
# 在数值计算中计算矩阵的算法中常常要判断算法的解是否收敛
# 这时最准确的方法是判断矩阵的最大特征值
# 但是矩阵的特征值得计算相对麻烦
# 所以可以近似的用范数代替
# 但是不够准确
# 但是很高效
# 理论上讲范数的概念属于赋范线性空间，
# 最重要的作用是诱导出距离，进而还可以研究收敛性。
# 对于矩阵而言没必要考虑范数的区别，
# 因为有限维空间的范数都等价(Minkowski定理)，
# 实际应用当中根据使用的难易程度来选取范数。
# 其中理论性质最好的是2-范数，因为它可以由内积来诱导，
# 同时和谱有着密切关联，所以常用来进行理论分析。 

In [38]:
#矩阵行列式
a = torch.tensor([[1.0,2],[3,4]])
print(torch.det(a))

tensor(-2.0000)


In [42]:
#矩阵特征值和特征向量
a = torch.tensor([[1.0,2],[-5,4]],dtype = torch.float)
print(torch.eig(a,eigenvectors=True))

#两个特征值分别是 -2.5+2.7839j, 2.5-2.7839j 

torch.return_types.eig(
eigenvalues=tensor([[ 2.5000,  2.7839],
        [ 2.5000, -2.7839]]),
eigenvectors=tensor([[ 0.2535, -0.4706],
        [ 0.8452,  0.0000]]))


In [44]:
#矩阵QR分解, 将一个方阵分解为一个正交矩阵q和上三角矩阵r
#QR分解实际上是对矩阵a实施Schmidt正交化得到q

a  = torch.tensor([[1.0,2.0],[3.0,4.0]])
q,r = torch.qr(a)
print(q,"\n")
print(r,"\n")
print(q@r)

tensor([[-0.3162, -0.9487],
        [-0.9487,  0.3162]]) 

tensor([[-3.1623, -4.4272],
        [ 0.0000, -0.6325]]) 

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000]])


In [45]:
#矩阵svd分解
#svd分解可以将任意一个矩阵分解为一个正交矩阵u,一个对角阵s和一个正交矩阵v.t()的乘积
#svd常用于矩阵压缩和降维
a=torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])

u,s,v = torch.svd(a)

print(u,"\n")
print(s,"\n")
print(v,"\n")

print(u@torch.diag(s)@v.t())

#利用svd分解可以在Pytorch中实现主成分分析降维

tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]]) 

tensor([9.5255, 0.5143]) 

tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]]) 

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])


In [46]:
# 四，广播机制
# Pytorch的广播规则和numpy是一样的:

# 1、如果张量的维度不同，将维度较小的张量进行 <扩展>，直到两个张量的维度都一样。

# 2、如果两个张量在某个维度上的长度是相同的，
# 或者其中一个张量在该维度上的长度为1，
# 那么我们就说这两个张量在该维度上是 <相容> 的。

# 3、如果两个张量在所有维度上都是相容的，它们就能使用 <广播>。

# 4、广播之后，每个维度的长度将取两个张量在该维度长度的 <较大值>。

# 5、在任何一个维度上，如果一个张量的长度为1，
# 另一个张量长度大于1，那么在该维度上，
# 就好像是对第一个张量进行了复制。

# torch.broadcast_tensors可以将多个张量根据广播规则转换成相同的维度。

a = torch.tensor([1,2,3]) #维度不够，剩下维度都是[1,2,3], 看下面代码。
b = torch.tensor([[0,0,0],[1,1,1],[2,2,2]])
print(b + a) 

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])


In [47]:
a_broad,b_broad = torch.broadcast_tensors(a,b)
print(a_broad,"\n")
print(b_broad,"\n")
print(a_broad + b_broad) 

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]) 

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]) 

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])
